#!/usr/bin/env bash
# Write a Bash script that displays a list of currently running processes.

# Requirements:

# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

# Use ps command to list all running processes with hierarchy
ps axjf

# Use ps command to list all running processes in user-oriented format
ps aux --sort=-%cpu


