#!/usr/bin/env bash
# Script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

counter=1

# Loop while the counter is less than or equal to 10
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    # Increment the counter
    counter=$((counter+1))
done

